# Generated by Django 5.2.7 on 2025-10-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
            ],
        ),
    ]
